"use strict";

// The logo in assets/ is a copy of the editor's master art, not a re-export of
// it. Those are not the same thing, and the difference is why this exists: the
// copy that lived here was an Illustrator export of the same drawing, using
// smooth-curve shorthand where the master writes its control points out. That
// is not an equivalent curve — it bent two of the inner arcs by about half a
// unit — and nothing here would ever have noticed, because nothing here reads
// the master at all.
//
//   node script/check-assets.js            report drift, exit 1 on any
//   node script/check-assets.js --write    copy the master over
//
// The editor is generated by script/generate-branding.js from a single vector,
// so the master is authoritative and this direction is the only one that makes
// sense: the site follows, and never the reverse.

const fs = require("fs");
const path = require("path");

const siteRoot = path.resolve(__dirname, "..");

// Where the editor checkout sits is already declared once, in api-sources.json,
// and CI lays both repositories out to match. Reading it back from there beats
// hard-coding a second ../lumine that could disagree with the first.
const { sources } = require(path.join(siteRoot, "api-sources.json"));
const metadata = sources.find((source) => source.packageMetadata)?.packageMetadata;
if (!metadata) throw new Error("One API source must provide a packageMetadata path.");
const editorRoot = path.resolve(siteRoot, path.dirname(metadata));

// lumine.svg is the favicon, the header and footer marks and the dot on the
// hero's "i"; lumine.png is the og:image. Both are whole files copied verbatim.
const ASSETS = ["lumine.svg", "lumine.png"];

const write = process.argv.includes("--write");
let drifted = 0;

for (const name of ASSETS) {
  const master = path.join(editorRoot, "resources", "app-icons", name);
  const copy = path.join(siteRoot, "assets", name);
  if (!fs.existsSync(master)) {
    console.log(`  no master  ${path.relative(siteRoot, master)}`);
    drifted++;
    continue;
  }
  const wanted = fs.readFileSync(master);
  const have = fs.existsSync(copy) ? fs.readFileSync(copy) : null;
  if (have && have.equals(wanted)) {
    console.log(`  ok         assets/${name}`);
    continue;
  }
  if (write) {
    fs.writeFileSync(copy, wanted);
    console.log(`  written    assets/${name}`);
    continue;
  }
  console.log(`  ${have ? "differs   " : "missing   "} assets/${name}`);
  drifted++;
}

if (drifted > 0) {
  console.log(`assets: ${drifted} out of date — run \`npm run assets:sync\``);
  process.exit(1);
}
console.log(`assets: ${ASSETS.length} in sync with the editor's app icons`);
